version: '3'

services:
  zobozdravstvo-ogrin.si:
    image: zobozdravstvo-ogrin.si
    restart: always
    build:
      context: ./
    ports:
      - "3030:3000"
      - "3031:3031"
    env_file:
      - .env  
